name:         ic
version:      0.1.0.0
github:       "0kauaa/IC"
license:      MIT
author:       "Kauã Santana"
maintainer:   "kauassilva0023@gmail.com"

# configurações compartilhadas globalmente
default-extensions:
  - DataKinds
  - TypeFamilies
  - TypeOperators
  - GADTs

ghc-options:
  - -Wall

# dependências compartilhadas globalmente
dependencies:
  - base >= 4.17 && < 5
  - cassava
  - bytestring
  - vector

# biblioteca
library:
  source-dirs: src

  # api global
  exposed-modules:
    # core estrutural
    - Core.Cat
    - Core.Learner
    - Core.Params
    - Core.Utils
    - Core.Multi
    - Core.MultiCat
    - Core.MultiLearner
    - Core.PROPs

    # modelos
    - Models.LinearRegressor
    - Models.PolynomialRegressor
    - Models.StandardRegressor
    - Models.LogisticRegressor
    - Models.Net

    # treinamento
    - Training.Training

    # dados
    - Dataset.Synthetic.Linear
    - Dataset.Synthetic.Polynomial
    - Dataset.Synthetic.Classified
    - Dataset.Empirical.IrisPCA2
    - Dataset.Empirical.Iris2
    - Dataset.Empirical.Banknotes

    # sandbox Learner
    - Sandbox.Activations
    - Sandbox.Layers
    - Sandbox.Outputs
    - Sandbox.Preprocessing
    - Sandbox.Routing

    # sandbox MultiLearner
    - Sandbox.Multi.Embed
    - Sandbox.Multi.Layers
    - Sandbox.Multi.Outputs

# arquivos executaveis
executables:

  # regressor linear
  linear-regressor:
    main: Main.hs
    source-dirs:
      - app/linear-regressor
    dependencies:
      - ic

  # regressor padronizado
  standard-regressor:
    main: Main.hs
    source-dirs:
      - app/standard-regressor
    dependencies:
      - ic

  # regressor polinomial
  polynomial-regressor:
    main: Main.hs
    source-dirs:
      - app/polynomial-regressor
    dependencies:
      - ic

  # regressor logistico
  logistic-regressor:
    main: Main.hs
    source-dirs:
      - app/logistic-regressor
    dependencies:
      - ic

  # rede neural
  small-net:
    main: Main.hs
    source-dirs:
      - app/small-net
    dependencies:
      - ic

  # dataset iris 
  iris-pca2:
    main: Main.hs
    source-dirs:
      - app/iris-pca2
    dependencies:
      - ic
  
  # playground do sandbox
  playground:
    main: Main.hs
    source-dirs:
      - app/playground
    dependencies:
      - ic
  
  # rede residual
  residual-net:
    main: Main.hs
    source-dirs:
      - app/residual-net
    dependencies:
      - ic
    ghc-options: -Wall
  
  # iris-multi
  iris-multi:
    main: Main.hs
    source-dirs:
      - app/iris-multi
    dependencies:
      - ic
    ghc-options: -Wall
  
  # bank-multi
  bank-multi:
    main: Main.hs
    source-dirs:
      - app/bank-multi
    dependencies:
      - ic
    ghc-options: -Wall


# testes
tests:
  test:
    main: Testes.hs
    source-dirs:
      - test
    dependencies:
      - ic