name:         ic
version:      0.1.0.0
github:       "0kauaa/IC"
license:      MIT
author:       "Kauã Santana"
maintainer:   "kauassilva0023@gmail.com"

extra-source-files:
  - README.md

# dependências globais
dependencies:
  - base >= 4.17 && < 5

# arquivos libs
library:
  source-dirs: src

  # api global
  exposed-modules:
    - Cat
    - Learner
    - Params
    - Models.LinearRegressor
    - Models.PolynomialRegressor
    - Models.StandardRegressor

  ghc-options:
    - -Wall

# arquivos executaveis
executables:

# regressor linear
  linear-regressor:
    main: Main.hs
    source-dirs:
      - app/linear-regressor
    dependencies:
      - ic
    ghc-options:
      - -Wall

# regressor padronizado
  standard-regressor:
    main: Main.hs
    source-dirs:
      - app/standard-regressor
    dependencies:
      - ic
    ghc-options:
      - -Wall

  # regressor polinomial
  polynomial-regressor:
    main:        Main.hs
    source-dirs:
      - app/polynomial-regressor
    dependencies:
      - ic
    ghc-options:
      - -Wall

# testes
tests:

  test:
    main: Testes.hs
    source-dirs:
      - test
    dependencies:
      - ic
    ghc-options:
      - -Wall