name:         ic
version:      0.1.0.0
github:       "0kauaa/IC"
license:      MIT
author:       "Kauã Santana"
maintainer:   "kauassilva0023@gmail.com"

extra-source-files:
  - README.md

# dependências globais
dependencies:
  - base >= 4.17 && < 5

# arquivos libs
library:
  source-dirs: src
  exposed-modules:
    - Cat
    - Learner
    - Params
  ghc-options: -Wall

# arquivos executaveis
executables:

# testes
  test:
    main:        Testes.hs
    source-dirs: test
    dependencies:
      - ic
    ghc-options: -Wall

# modelos
  models:
    main:        Main.hs
    source-dirs: models
    other-modules:
      - LinearRegressor
      #- NormalLinearRegressor
      #- PolinomialRegressor
    dependencies:
      - ic
    ghc-options: -Wall